name: Publish to NPM
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm run build
      - run: npm run build:types
      - uses: JS-DevTools/npm-publish@v3
        with:
            access: public
            token: ${{ secrets.NPM_AUTH_TOKEN }}